version: '3.8'

services:
  gauresh-app:
    build: .
    ports:
      - "80:5000"
    environment:
      - S3_BUCKET_NAME=gauresh-assignment
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ~/.aws:/root/.aws:ro